package com.app.opencolegio.domain;
// Generated 07-mar-2013 21:19:49 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Colegios generated by hbm2java
 */
@Entity
@Table(name="colegios"
    ,catalog="prueba"
)
public class Colegios  implements java.io.Serializable {


     private Integer idColegio;
     private String nombre;

    public Colegios() {
    }

    public Colegios(String nombre) {
       this.nombre = nombre;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_colegio", unique=true, nullable=false)
    public Integer getIdColegio() {
        return this.idColegio;
    }
    
    public void setIdColegio(Integer idColegio) {
        this.idColegio = idColegio;
    }
    
    @Column(name="nombre", nullable=false, length=300)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


